/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./js/**/*.{js,ts}",
    "./css/**/*.css"
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f9f9f8',
        'surface-dim': '#dadad9',
        'surface-bright': '#f9f9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f3',
        'surface-container': '#eeeeed',
        'surface-container-high': '#e8e8e7',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#3f4944',
        'inverse-surface': '#2f3130',
        'inverse-on-surface': '#f1f1f0',
        'outline': '#6f7a74',
        'outline-variant': '#bec9c3',
        'surface-tint': '#086b53',
        'primary': '#005440',
        'on-primary': '#ffffff',
        'primary-container': '#0f6e56',
        'on-primary-container': '#9aedcf',
        'inverse-primary': '#84d6b9',
        'primary-fixed': '#a0f3d4',
        'primary-fixed-dim': '#84d6b9',
        'on-primary-fixed': '#002117',
        'on-primary-fixed-variant': '#00513e',
        'secondary': '#885200',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdad4e',
        'on-secondary-container': '#704200',
        'secondary-fixed': '#ffdcbb',
        'secondary-fixed-dim': '#ffb869',
        'on-secondary-fixed': '#2b1700',
        'on-secondary-fixed-variant': '#673d00',
        'tertiary': '#3b4d48',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#536560',
        'on-tertiary-container': '#cee1db',
        'tertiary-fixed': '#d3e7e0',
        'tertiary-fixed-dim': '#b7cbc4',
        'on-tertiary-fixed': '#0d1f1b',
        'on-tertiary-fixed-variant': '#394a45',
        'background': '#f9f9f8',
        'on-background': '#1a1c1c',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a'
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px'
      },
      spacing: {
        'gutter': '1.25rem',
        'gutter-desktop': '2rem',
        'margin': '1.25rem',
        'margin-desktop': '3rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem'
      },
      fontFamily: {
        'sans': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'editorial': ['Newsreader', 'Georgia', 'serif'],
        'display': ['Newsreader', 'Georgia', 'serif'],
        'display-mobile': ['Newsreader', 'Georgia', 'serif'],
        'editorial-quote': ['Newsreader', 'Georgia', 'serif'],
        'headline-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif']
      },
      fontSize: {
        'display': ['2.75rem', { lineHeight: '3.25rem', letterSpacing: '-0.015em', fontWeight: '400' }],
        'display-mobile': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['1.375rem', { lineHeight: '1.875rem', letterSpacing: '-0.005em', fontWeight: '500' }],
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '0em', fontWeight: '500' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '500' }],
        'editorial-quote': ['1.25rem', { lineHeight: '1.875rem', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-lg': ['1.0625rem', { lineHeight: '1.625rem', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['0.9375rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '500' }]
      }
    }
  },
  plugins: []
};
